<?php

include "main_conf.php";

$AMS_AUTONOMOUS_DB_HOST = $DB_EXAT_HOST = $DB_HOST;
$AMS_AUTONOMOUS_DB_USER = $DB_EXAT_USER = $DB_USER;
$AMS_AUTONOMOUS_DB_PASSWD = $DB_EXAT_PASSWD = $DB_PASSWD;
$AMS_AUTONOMOUS_DB_NAME = $DB_EXAT_NAME = $DB_NAME;